project:
  type: website
  output-dir: docs

website:
  title: "Chelsey Legacy"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - teaching.qmd
      - research.qmd
      - more.qmd
      - href: "files/Legacy-CV.pdf"
        text: CV
format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

