---
title: "Teaching"
---

My teaching practices stem from my knowledge of statistics and my studies in educational psychology and measurement. In my classroom, students learn to think critically about statistics through collaboration with their peers in small-group, guided discovery learning activities and using thoughtfully developed assessments and curriculum informed by research. I aim to provide students with the tools they need to be thoughtful data consumers, producers, and communicators while creating a classroom atmosphere where students feel welcome to ask questions and participate in meaningful discussions.

**I currently teach the master's level introductory statistics courses:**

-   *EPSY 5261: Introductory Statistical Methods*

-   *EPSY 5262: Intermediate Statistical Methods*

**And I oversee an undergraduate data visualization course:**

-   *EPSY 1261: Understanding Data Stories Through Visualization and Computing*

**Past Courses Taught:**

-   UMN \| EPSY 3264

-   ISU \| STAT 104

-   ISU \| STAT 101
